from shared_config import *

# DNS Configuration
DNS_RESOLVER_IP = LOCAL_IP
DNS_RESOLVER_PORT = DNS_PORT
CAMERA_DOMAIN_NAME = CAMERA_DOMAIN_NAME
CAMERA_SERVER_PORT = CAMERA_SERVER_PORT

# Discovery Configuration
DISCOVERY_SERVER_IP = LOCAL_IP
DISCOVERY_SERVER_PORT = DISCOVERY_PORT
DISCOVERY_ENABLED = True

# Fallback server IP (in case DNS fails)
FALLBACK_SERVER_IP = LOCAL_IP

# Camera Configuration
CAMERA_INDEX = CAMERA_INDEX
CAMERA_WIDTH = CAMERA_WIDTH
CAMERA_HEIGHT = CAMERA_HEIGHT

# DNS Resolution Settings
DNS_TIMEOUT = DNS_TIMEOUT
DNS_RETRIES = DNS_RETRIES